name: CI for Swift Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Install dependencies
        run: |
          if [ -f Podfile ]; then
            sudo gem install cocoapods
            pod install
          else
            echo "No Podfile found, skipping CocoaPods installation"
          fi

      - name: Build project
        run: |
          xcodebuild clean build -project swift_app.xcodeproj -scheme swift_app -destination "generic/platform=iOS Simulator"

      - name: Run tests
        run: |
          xcodebuild test -project swift_app.xcodeproj -scheme swift_app -destination "generic/platform=iOS Simulator"
